### ISSUE TITLE
Disconnected event

### ISSUE THREAD

**Issue by 0xAnakin** [dgurkaynak/nodeshout#13]
Is there a way to get notified when you get disconnected from the icecast server?

**Comment by dgurkaynak** [comment]
Hey @0xAnakin, sorry for late response. 

I think I've found it. Both `shout.open()`, `shout.send()` and `shout.setMetadata()` methods return a code indicating whether the operation is successful or not. You can see what method can return which codes from [the original libshout docs](https://www.aelius.com/njh/libshout-doc/libshout.html).

If disconnected, `shout.send()` returns `-2` which is [`nodeshout.ErrorTypes.NOCONNECT`](https://github.com/dgurkaynak/nodeshout/blob/master/src/index.js#L65-L77). You can catch the disconnection event like this.

**Comment by 0xAnakin** [comment]
Yes I did the same thing after each send I'm checking if the data have been sent otherwise i fire an error event.
