### ISSUE TITLE
Metadata at given time

### ISSUE THREAD

**Issue by daslicht** [dgurkaynak/nodeshout#3]
Hi,
let's say we have a DJ Mix of multiple songs wich is one long audio file.
Is there a way to determine the current position of the stream so that we can inject the correct metadata ?

**Comment by dgurkaynak** [comment]
Hey,

There is no easy way to do this, I guess. My approach would be setting up a custom pass-through stream between `FileReadStream` and `ShoutStream`. Then you can calculate the position according to data length and source encoding.

**Comment by daslicht** [comment]
Yeah that was my approach either :) but the calculation is anything else than trivial :D
