### ISSUE TITLE
Ogg is not working

### ISSUE THREAD

**Issue by omermecitoglu** [dgurkaynak/nodeshout#5]
mp3 is fine. But I can't play ogg files. 

`var song = './mysong.ogg';`
`shout.setFormat(0); // 0=ogg, 1=mp3`

"Read 65536 bytes of data" messages flow too fast, then stream stops, listeners can't hear anything.

**Comment by dgurkaynak** [comment]
Hey @omermecitoglu, sorry for late response. I believe you forgot setting format to ogg.  I have just tried this and also update one of the demos as playing ogg file. Check out this commit => https://github.com/dgurkaynak/nodeshout/commit/513b3d5b8e8327dcc63fbb82593f91c739cc8b7c

**Comment by coolaj86** [comment]
I also have this problem, despite `setFormat(0)` being set.

Are any of the `shout.setAudioInfo()` parameters different for Ogg?

**Comment by omermecitoglu** [comment]
My ogg file was broken. I have converted it with an online converter and didn't even check if it was working.

**Comment by dgurkaynak** [comment]
According to [libshout docs](https://www.aelius.com/njh/libshout-doc/libshout.html#audio_info_constants) there are just 4 audio info parameters:

> SHOUT_AI_BITRATE - Used to specify the nominal bitrate of the stream.
SHOUT_AI_SAMPLERATE - Used to specify the samplerate of the stream.
SHOUT_AI_CHANNELS - Used to specify the number of channels (usually one or two).
SHOUT_AI_QUALITY - Used to specify the Ogg Vorbis encoding quality of the stream.

However `setAudioInfo` parameters should be irrelevant, they're for outgoing stream. The issue you have is about reading an ogg file. As @omermecitoglu mentioned, ensure your ogg file is working. You can try with [sample ogg file](https://github.com/dgurkaynak/nodeshout/blob/master/music/test.ogg) provided in the repo.
