### ISSUE TITLE
error when trying to use module

### ISSUE THREAD

**Issue by danielpmc** [dgurkaynak/nodeshout#8]
Error: ENOENT: no such file or directory, open 'libshout.so'

Some enviroment info: 
Node version: 10.19.0
NPM version: 6.13.4

**Comment by dgurkaynak** [comment]
Is `libshout` installed on your system?

**Comment by danielpmc** [comment]
yes. i just reinstalled it and now getting: 
binding.target.mk:111: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1

**Comment by dgurkaynak** [comment]
What is your OS, and do you get this error while `npm install nodeshout`, or on runtime?

**Comment by danielpmc** [comment]
My OS is linux. i was able to fix it by downgrading my NodeJS Version to 8.10.0.
